services:
  user-db:
    image: mysql:8.0.30
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: userDB

  user-api:
    links:
      - user-db
    restart: on-failure
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DEBUG: user:*

networks:
  default:
    external:
      name: exchange-user-rate
